
with cte_mnpr as(
select menu_item_name,
       menu_item_number,
       price, 
       cost,
       effective_from,
       tax_class_number,
       menu_level,
       price_level,
       level_name,
       revenue_center_name,
       revenue_center_number,
       revenue_center_master_name,
       revenue_center_master_number,
       menu_item_master_name,
       menu_item_master_number,
       major_group_name,
       major_group_number,
       major_group_master_name,
       major_group_master_number,
       family_group_name,
       family_group_number,
       family_group_master_name,
       family_group_master_number,
       --using sys_filename to extract store number and date field
       SPLIT_PART(sys_filename,'_',2) as store_number,
       TO_DATE(SPLIT_PART(SPLIT_PART(sys_filename,'_',3), '.',1), 'mmddyy')  as business_date     
from {{source("stage_simphony", "mnpr")}}
)
select menu_item_name,
    menu_item_number,
    price, 
    cost,
    effective_from,
    tax_class_number,
    menu_level,
    price_level,
    level_name,
    revenue_center_name,
    revenue_center_number,
    revenue_center_master_name,
    revenue_center_master_number,
    menu_item_master_name,
    menu_item_master_number,
    major_group_name,
    major_group_number,
    major_group_master_name,
    major_group_master_number,
    family_group_name,
    family_group_number,
    family_group_master_name,
    family_group_master_number,
    store_number,
    business_date,
    md5(
        concat(
        'mnpr',
        menu_item_number,
        price_level, 
        revenue_center_number,
        revenue_center_name, 
        revenue_center_master_number,
        revenue_center_master_name, 
        store_number, 
        business_date)
    ) as pk_mnpr
from cte_mnpr
